version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      - NODE_ENV=production
    volumes:
      - ./screenshots:/usr/src/app/screenshots
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
