version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    cap_add:
      - SYS_ADMIN
  client:
    build: ./client
    ports:
      - "3001:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
