version: '3'
services:
  server:
    image: fatemasoliman427/ottomate-server:arm64
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - CLIENT_ORIGIN=http://3.29.35.64
    cap_add:
      - SYS_ADMIN
  client:
    image: fatemasoliman427/ottomate-client:latest
    ports:
      - "80:80"
    depends_on:
      - server